#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "drupal"
name = "Drupal"
description.en = "Content management framework"
description.fr = "Système de gestion de contenu"

version = "2026.07.27~ynh1"

maintainers = ["yalh76"]

[upstream]
license = "GPL-2.0-or-later"
website = "https://www.drupal.org"
admindoc = "https://www.drupal.org/docs/9"
code = "https://github.com/drupal/drupal"
cpe = "cpe:2.3:a:drupal:drupal"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/drupal"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

    [install.install_profil]
    ask.en = "Choose the Drupal install profile to use"
    ask.fr = "Choisissez le profile d'installation de Drupal"
    type = "select"
    choices = ["minimal", "standard"]
    default = "standard"

[resources]

    [resources.sources]

    [resources.sources.main]
    prefetch = false
    url = "https://github.com/drupal/drupal/archive/refs/tags/10.6.15.tar.gz"
    sha256 = "9c8883b72b10ef398a1bd6b436f7abe35b083fc7540ffa15aae9b58aebaab695"

    autoupdate.strategy = "latest_github_tag"
    autoupdate.version_regex = "^(10.*)$"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "php8.4-fpm",
        "php8.4-cli",
        "php8.4-gd",
        "php8.4-mysql",
        "php8.4-xml",
        "php8.4-ldap",
        "php8.4-mbstring",
        "php8.4-uploadprogress",
        "php8.4-apcu",
        "php8.4-json",
        "php8.4-simplexml",
        "php8.4-curl",
        "php8.4-readline",
        "curl",
        "libzip-dev",
        "mariadb-server",
    ]

    [resources.database]
    type = "mysql"

    [resources.composer]
    version = "2.8.3"
