#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

# this will most likely adjust NGINX config correctly
ynh_config_change_url_nginx

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================

ynh_config_add --template="example.site.yml" --destination="$install_dir/drush/sites/$app.site.yml"
ynh_replace --match=$old_domain --replace=$new_domain --file="$install_dir/web/sites/default/settings.php"
ynh_backup_if_checksum_is_different "$install_dir/web/sites/default/settings.php"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
