#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================
# UPDATE DRUSH ALIAS
#=================================================
ynh_script_progression "Updating Drush alias..."

ynh_config_add --template="example.site.yml" --destination="$install_dir/drush/sites/$app.site.yml"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
