#!/bin/bash

source _common.sh
source ynh_add_swap
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the dedicated NGINX config
ynh_config_remove_nginx

# Remove the dedicated PHP-FPM config
ynh_config_remove_phpfpm

# Remove the cron file
ynh_safe_rm "/etc/cron.d/$app"

#=================================================
# REMOVE SWAP
#=================================================
ynh_script_progression "Removing swap..."

ynh_del_swap

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
