#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

ynh_app_setting_set_default --key=php_upload_max_filesize --value=512M
ynh_app_setting_set_default --key=php_post_max_size --value=512M
ynh_app_setting_set_default --key=php_memory_limit --value=512M

if [ -d "$install_dir/$app" ]; then
  mv "$install_dir/$app" "$install_dir/web"
  mv "$install_dir/drush/sites/$app.site.yml" "$install_dir/drush/sites/self.site.yml"
fi

#=================================================
# CREATE DRUSH ALIAS
#=================================================
ynh_script_progression --message="Creating Drush alias..." --weight=1

mkdir -p "$install_dir/drush/sites/"
ynh_config_add --template="example.site.yml" --destination="$install_dir/drush/sites/$app.site.yml"

#=================================================
# UPGRADE COMPOSER
#=================================================
ynh_script_progression "Upgrading Composer..."

ynh_config_add --template="composer.json" --destination="$install_dir/composer.json"

ynh_composer_install
chmod +w $install_dir/web/sites/default/
ynh_composer_exec update --no-dev

#=================================================
# CREATE DRUSH ALIAS
#=================================================
ynh_script_progression "Creating Drush alias..."

install -d -m 750 -o $app -g $app "$install_dir/drush/sites/"
ynh_config_add --template="example.site.yml" --destination="$install_dir/drush/sites/self.site.yml"

#=================================================
# UPGRADE DRUPAL
#=================================================
ynh_script_progression "Upgrading Drupal..."

ynh_backup_if_checksum_is_different "$install_dir/web/sites/default/settings.php"

update-alternatives --set php /usr/bin/php$php_version

pushd "$install_dir"
	_ynh_exec_with_drush_php drush "@$app" state:set system.maintenance_mode 1 --input-format=integer
	_ynh_exec_with_drush_php "php$php_version" composer.phar update drupal/core webflo/drupal-core-require-dev --with-dependencies
	_ynh_exec_with_drush_php "php$php_version" composer.phar update --with-dependencies
	_ynh_exec_with_drush_php drush "@$app" -y updatedb
	_ynh_exec_with_drush_php drush "@$app" -y config-set system.performance css.preprocess 0
	_ynh_exec_with_drush_php drush "@$app" -y config-set system.performance js.preprocess 0
	_ynh_exec_with_drush_php drush "@$app" cache:rebuild
	_ynh_exec_with_drush_php drush "@$app" state:set system.maintenance_mode 0 --input-format=integer
popd

ynh_store_file_checksum "$install_dir/web/sites/default/settings.php"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_config_add --template="cron" --destination="/etc/cron.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
